spring:
    datasource:
        url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
        username: ${PGUSE}
        password: ${PGPASSWORD}
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: create
